In [5]:
!pip install chembl_webresource_client
from chembl_webresource_client.new_client import new_client
target_api = new_client.target
results = target_api.search('EGFR')
results_list = list(results)
print(results_list[0])

Requirement already satisfied: chembl_webresource_client in C:\Users\admin\anaconda3\Lib\site-packages (0.10.9)
Requirement already satisfied: urllib3 in C:\Users\admin\anaconda3\Lib\site-packages (from chembl_webresource_client) (2.7.0)
Requirement already satisfied: requests>=2.18.4 in C:\Users\admin\anaconda3\Lib\site-packages (from chembl_webresource_client) (2.34.2)
Requirement already satisfied: requests-cache~=1.2 in C:\Users\admin\anaconda3\Lib\site-packages (from chembl_webresource_client) (1.3.3)
Requirement already satisfied: easydict in C:\Users\admin\anaconda3\Lib\site-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: attrs>=21.2 in C:\Users\admin\anaconda3\Lib\site-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Requirement already satisfied: cattrs>=22.2 in C:\Users\admin\anaconda3\Lib\site-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\admin\anaconda3\Lib\site-packages (from requests-cache~=1.2->chembl_webresource_client) (4.9.4)
Requirement already satisfied: url-normalize>=2.0 in C:\Users\admin\anaconda3\Lib\site-packages (from requests-cache~=1.2->chembl_webresource_client) (3.0.0)
Requirement already satisfied: typing-extensions>=4.14.0 in C:\Users\admin\anaconda3\Lib\site-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\admin\anaconda3\Lib\site-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\admin\anaconda3\Lib\site-packages (from requests>=2.18.4->chembl_webresource_client) (3.18)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\admin\anaconda3\Lib\site-packages (from requests>=2.18.4->chembl_webresource_client) (2026.6.17)

Exception: Error getting schema from url https://www.ebi.ac.uk/chembl/api/data/spore with status 500 and msg <!doctype html>
<html lang="en" class="vf-no-js">
  <head>
    <script>
// Detect if JS is on and swap vf-no-js for vf-js on the html element
(function(H){H.className=H.className.replace(/\bvf-no-js\b/,'vf-js')})(document.documentElement);
</script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" media="all" href="/css/styles.css?" /> -->
    <title>Error: 500 | EMBLâs European Bionformatics Institute</title>



    <link rel="icon" type="image/x-icon"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/favicon.ico" />
<link rel="icon" type="image/png"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/favicon-32x32.png" />
<link rel="icon" type="image/png" sizes="192Ã192"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/android-chrome-192x192.png" />
<!-- Android (192px) -->
<link rel="apple-touch-icon-precomposed" sizes="114x114"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/apple-icon-114x114.png" />
<!-- For iPhone 4 Retina display (114px) -->
<link rel="apple-touch-icon-precomposed" sizes="72x72"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/apple-icon-72x72.png" />
<!-- For iPad (72px) -->
<link rel="apple-touch-icon-precomposed" sizes="144x144"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/apple-icon-144x144.png" />
<!-- For iPad retinat (144px) -->
<link rel="apple-touch-icon-precomposed"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/apple-icon-57x57.png" />
<!-- For iPhone (57px) -->
<link rel="mask-icon"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/safari-pinned-tab.svg"
  color="#ffffff" /> <!-- Safari icon for pinned tab -->
<meta name="msapplication-TileColor" content="#2b5797" /> <!-- MS Icons -->
<meta name="msapplication-TileImage"
  content="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/mstile-144x144.png" />






    <!-- Search indexing optimisations -->
    <meta class="swiftype" name="what" data-type="string" content="none" />
    <meta class="swiftype" name="where" data-type="string" content="EMBL-EBI" />


    <!-- Descriptive meta -->
    <meta name="title" content="Error: 500">
    <meta name="author" content="European Bioinformatics Institute">
    <meta name="robots" content="index, follow">
    <meta name="keywords" content="">
    <meta name="description" content="">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://www.ebi.ac.uk/info/error-pages/500-standalone/">
    <meta property="og:title" content="Error: 500">
    <meta property="og:description" content="">


    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="og:url" content="https://www.ebi.ac.uk/info/error-pages/500-standalone/">
    <meta property="twitter:title" content="Error: 500">
    <meta property="twitter:description" content="">


    <!-- Content descriptors -->
    <meta name="embl:who" content="EMBL-EBI Web Dev">
    <meta name="embl:where" content="EMBL-EBI">
    <meta name="embl:what" content="none">
    <meta name="embl:active" content="where">

    <!-- Content role -->
    <meta name="embl:utility" content="10">
    <meta name="embl:reach" content="0">

    <!-- Page infromation -->
    <meta name="embl:maintainer" content="EMBL-EBI Web Dev">
    <meta name="embl:last-review" content="2021.04.01">
    <meta name="embl:review-cycle" content="365">
    <meta name="embl:expiry" content="never">

    <!-- analytics -->
    <meta name="vf:page-type" content="404;dimension1">

    <!-- CSS only -->
<link rel="stylesheet" href="https://assets.emblstatic.net/vf/v2.5.7/css/styles.css">
<!-- JS -->
<script src="https://assets.emblstatic.net/vf/v2.5.7/scripts/scripts.js"></script>
<head>
  <body class="vf-body vf-stack vf-stack--400">
    <style>head, title, link, meta, style, script {--vf-stack-margin--custom: 0; }</style>

    <!-- See the EBI Header Footer docs: https://stable.visual-framework.dev/components/ebi-header-footer -->

    <link rel="stylesheet" href="https://assets.emblstatic.net/vf/v2.4.5/assets/ebi-header-footer/ebi-header-footer.css" type="text/css" media="all">
    <header id="masthead-black-bar" class="clearfix masthead-black-bar | ebi-header-footer vf-content vf-u-fullbleed"></header>




<style>
  .embl-grid {
    margin-bottom: 48px;
  }
</style>

<section class="vf-intro" id="500">

  <div><!-- empty --></div>

  <div class="vf-stack">

  <h1 class="vf-intro__heading ">Error: 500</h1>
<p class="vf-lede">There was a technical error.</p>


<p class="vf-intro__text">Something has gone wrong with our web server when attempting to make this page.</p><p class="vf-intro__text">Unfortunately, the service you are trying to access is currently unavailable. <br>Please try again later.</p>
  </div>
</section>


<section class="embl-grid embl-grid--has-centered-content">
  <div></div>
 <section>
      <form id="ebi_search" action="/ebisearch/search.ebi" class="vf-form vf-form--search vf-form--search--mini | vf-sidebar vf-sidebar--end">
        <div class="vf-sidebar__inner" style="flex-wrap: nowrap;">
          <div class="vf-form__item">
            <label class="vf-form__label vf-u-sr-only | vf-search__label" for="searchitem">Search</label>
            <input name="query" type="search" placeholder="Find a gene, protein or chemical" id="searchitem" class="vf-form__input" required="" spellcheck="false" data-ms-editor="true">
            <input name="requestFrom" id="requestFrom" type="hidden" class="vf-form__input" value="ebi_index">
          </div>
          <div class="vf-form__item">
            <select name="db" id="db" tabindex="1" class="vf-form__select" style="max-width: 150px">
              <option value="allebi">All</option>
              <optgroup label="Science search">
                <option value="genomes">Genomes &amp; metagenomes</option>
                <option value="nucleotideSequences">Nucleotide sequences</option>
                <option value="proteinSequences">Protein sequences</option>
                <option value="smallMolecules">Small molecules</option>
                <option value="geneExpression">Gene expression</option>
                <option value="geneDiseaseAssociations">Gene-Disease Associations</option>
                <option value="diseases">Diseases</option>
                <option value="molecularInteractions">Molecular interactions</option>
                <option value="reactionsPathways">Reactions &amp; pathways</option>
                <option value="proteinFamilies">Protein families</option>
                <option value="literature">Literature</option>
                <option value="ontologies">Samples &amp; ontologies</option>
              </optgroup>
              <optgroup label="Search web content">
                <option value="ebiweb_people">EMBL-EBI People</option>
                <option value="ebiweb">EMBL-EBI web</option>
                <!-- <option value="ebiweb">EMBL web</option> -->
              </optgroup>
            </select>
          </div>


          <button type="submit" class="vf-search__button | vf-button vf-button--primary">
            <span class="vf-button__text">Search</span>
          </button>
        </div>
      </form>
      <p class="vf-text-body--5 vf-u-margin__bottom--0">
        Example searches: <a class="vf-link" href="/ebisearch/search.ebi?db=allebi&amp;requestFrom=ebi_index&amp;query=blast">blast</a>
        <a class="vf-link" href="/ebisearch/search.ebi?db=allebi&amp;query=keratin&amp;requestFrom=ebi_index">keratin</a>
        <a class="vf-link" href="/ebisearch/search.ebi?db=allebi&amp;query=bfl1&amp;requestFrom=ebi_index">bfl1</a>
        | <a class="vf-link" href="https://www.ebi.ac.uk/ebisearch/overview.ebi/about">About EBI Search</a>
      </p>
    </section>
</section>

<section class="embl-grid">
  <div></div>
  <div class="vf-content">
    <h3>Need assistance?</h3>
    <a class="vf-button vf-button--primary" href="https://www.ebi.ac.uk/support/error">Contact our support team</a>
  </div>
</section>

    <!-- embl global footer -->


<!-- embl-ebi global footer -->
<link rel="import" href="https://www.embl.org/api/v1/pattern.html?filter-content-type=article&filter-id=106902&pattern=node-body&source=contenthub" data-target="self" data-embl-js-content-hub-loader>

    <script src="https://assets.emblstatic.net/vf/v2.4.9/scripts/scripts.js"></script>
<!--
  When using legacy EBI 1.x JS, we disable the old cookie banner.
  https://stable.visual-framework.dev/components/ebi-header-footer/
  -->
<div class="vf-u-display-none" data-protection-message-disable="true"></div>

<!-- IE11 polyfill JS -->
<script nomodule crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?flags=gated&features=default"></script>
<!-- <script src="/scripts/scripts.js?"></script> -->
<script defer="defer" src="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/js/script.js"></script>
<link rel="stylesheet" href="//ebi.emblstatic.net/web_guidelines/EBI-Icon-fonts/v1.3/fonts.css" type="text/css" media="all" />

<!-- Google Analytics -->
<script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', 'UA-629242-1', 'auto');
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>
<!-- End Google Analytics -->

<script type="text/javascript">
  document.addEventListener("DOMContentLoaded", function(event) {

        //- Code to execute when only the HTML document is loaded.
        //- This doesn't wait for stylesheets,
        // images, and subframes to finish loading.
  });
</script>

  </body>
</html>

In [4]:
# 1. We create a "Mock" (simulated) list of targets, just like ChEMBL would return.
mock_results_from_chembl = [
    {
        'pref_name': 'epidermal growth factor receptor',
        'organism': 'Homo sapiens',
        'target_type': 'SINGLE PROTEIN',
        'target_chembl_id': 'CHEMBL203'
    },
    {
        'pref_name': 'ErbB-2 receptor',
        'organism': 'Mus musculus',
        'target_type': 'SINGLE PROTEIN',
        'target_chembl_id': 'CHEMBL1824'
    },
    {
        'pref_name': 'EGFR Protein Complex',
        'organism': 'Homo sapiens',
        'target_type': 'PROTEIN COMPLEX',
        'target_chembl_id': 'CHEMBL2363064'
    }
]
# We only want 'Homo sapiens' and 'SINGLE PROTEIN'
for target in mock_results_from_chembl:
    organism = target['organism']
    target_type = target['target_type']
    if organism == 'Homo sapiens' and target_type == 'SINGLE PROTEIN':
        name = target['pref_name']
        chembl_id = target['target_chembl_id']
        print(f"FOUND TARGET! Name: {name} | ID: {chembl_id}")

FOUND TARGET! Name: epidermal growth factor receptor | ID: CHEMBL203

In [21]:
mock_database = [
    {
        'pref_name': 'Epidermal frowth factor receptor (EGFR)',
        'organism': 'Homo sapiens',
        'target_type': 'SINGLE PROTEIN',
        'clinical_phase': '4',
        'target_chembl_id': 'CHEMBL203'
    },
    {
        'pref_name': 'Beta-secretase 1 (BACE1)',
        'organism': 'Homo sapiens',
        'target_type': 'SINGLE PROTEIN',
        'clinical_phase': '3',
        'target_chembl_id': 'CHEMBL4822',
    },
    {
        'pref_name': 'JAK2 kinase',
        'organism': 'Mus musculus',
        'target_type': 'SINGLE PROTEIN',
        'clinical_phase': '4',
        'target_chembl_id': 'CHEMBL2971'
    },
    {
        'pref_name': 'Estrogen receptor alpha',
        'organism': 'Homo sapiens',
        'target_type': 'SINGLE PROTEIN',
        'clinical_phase': '4',
        'target_chembl_id': 'CHEMBL206'
    }
]
for target in mock_database:
    organism = target['organism']
    target_type = target['target_type']
    clinical_phase = target['clinical_phase']
    if organism == "Homo sapiens" and target_type == "SINGLE PROTEIN" and clinical_phase == "4":
        name = target['pref_name']
        ID = target['target_chembl_id']
        print(f"FOUND TARGET! name: {name:<40} | ID: {ID}")

FOUND TARGET! name: Epidermal frowth factor receptor (EGFR)  | ID: CHEMBL203
FOUND TARGET! name: Estrogen receptor alpha                  | ID: CHEMBL206

In [26]:
raw_bioactivity_data = [
    {
        'molecule_name': 'Gefitinib',
        'canonical_smiles':'COCCOCCOCCO...',
        'bioactivity_details': {
            'type': 'IC50',
            'value': 35, 
            'unit': 'nM'
        }
    },
    {
        'molecule_name': 'Aspirin',
        'canonical_smiles': 'CC(=O)OC1=CC=CC=C1C(=O)O)',
        'bioactivity_details': {
            'type': 'IC50',
            'value': 5000,
            'unit': 'nM'
        }
    },
    {
        'molecule_name': 'Osimertinib',
        'canonical_smiles': 'CN(C)CC=CC(=O)N...',
        'bioactivity_details': {
            'type': 'IC50',
            'value': 15,
            'unit': 'nM'
        }
    }
]
for compound in raw_bioactivity_data :
    details = compound.get('bioactivity_details', {})
    bio_type = details.get('type', 'Unknown')
    bio_value = details.get('value', 999)
    if bio_type == "IC50" and bio_value < 100:
        name = compound.get('molecule_name', 'Nameless')
        print(f"DETECT QUALIFIED COMPOUND: {name:<20} | IC50_value = {bio_value} ")

DETECT QUALIFIED COMPOUND: Gefitinib            | IC50_value = 35
DETECT QUALIFIED COMPOUND: Osimertinib          | IC50_value = 15

In [35]:
messy_bioactivity_data = [
    {
        'molecule_name': 'Gefitinib',
        'bioactivity_details': {
            'type': 'IC50',
            'value': 35, 
            'unit': 'nM' # Already in nM!
        }
    },
    {
        'molecule_name': 'Aspirin',
        'bioactivity_details': {
            'type': 'IC50',
            'value': 5.2,
            'unit': 'uM' # <-- Needs to be converted! (5.2 * 1000 = 5200 nM)
        }
    },
    {
        'molecule_name': 'Osimertinib',
        'bioactivity_details': {
            'type': 'IC50',
            'value': 0.015,
            'unit': 'uM' # <-- Needs to be converted! (0.015 * 1000 = 15 nM)
        }
    }
]
for compound in messy_bioactivity_data:
    details = compound.get('bioactivity_details', {})
    bio_value = details.get('value', 999)
    bio_type = details.get('unit', {})
    name = compound.get('molecule_name', 'nameless')
    if bio_type == "uM":
        bio_value = bio_value * 1000
        bio_type = "nM"
    if bio_value < 100 :
        print(f"FINAL COMPOUND {name:<20} | IC50 value: {bio_value:.2f}")

FINAL COMPOUND Gefitinib            | IC50 value: 35.00
FINAL COMPOUND Osimertinib          | IC50 value: 15.00

In [1]:
from chembl_webresource_client.new_client import new_client

try:
    # 1. Access target API
    target_api = new_client.target
    
    # 2. Search for human EGFR
    print("Connecting to ChEMBL in Europe...")
    results = target_api.filter(target_organism="Homo sapiens", target_type="SINGLE PROTEIN").search("EGFR")
    
    # 3. Try to pull the first match
    first_match = list(results)[0]
    print("\n✅ CONNECTION RECOVERED!")
    print(f"Target Name: {first_match.get('pref_name')}")
    print(f"ChEMBL ID:   {first_match.get('target_chembl_id')}")

except Exception as error:
    print("\n❌ Server is still undergoing maintenance.")
    print(f"Error details: {error}")

Connecting to ChEMBL in Europe...

❌ Server is still undergoing maintenance.
Error details: You can add filters to refine search but you can't search among prefiltered results

In [5]:
import pandas as pd
messy_compounds = [
    {
        'molecule_name': 'Gefitinib',
        'bioactivity_details': { 
            'type': 'IC50',
            'value': 35,
            'unit': 'nM'
        }
    },
    {
        'molecule_name': 'Asipirin',
        'bioactivity_details': {
            'type': 'IC50',
            'value': 5.2,
            'unit': 'uM'
        }
    },
    {
        'molecule_name': 'Osimertinib',
        'bioactivity_details': {
            'type': 'IC50',
            'value': 0.015,
            'unit': 'uM'
        }
    },
    {
        'molecule_name': 'Lapatinib',
        'bioactivity_details': {
            'type': 'IC50',
            'value': 120,
            'unit': 'nM'
        }
    }
]
cleaned_list = []
for compound in messy_compounds:
    details = compound.get('bioactivity_details', {})
    bio_value = details.get('value', 999)
    unit = details.get('unit', 'Unknown')
    name = compound.get('molecule_name', 'Nameless')
# Standarlize uM to nM
    if unit == 'uM':
        bio_value = bio_value * 1000
        unit = 'nM'
    if bio_value < 100:
        cleaned_record = {
            'Molecule_name': name,
            'IC50 (nM)': round(bio_value, 2),
            'Status': 'Potent'
        }
        cleaned_list.append(cleaned_record)
df = pd.DataFrame(cleaned_list)
df

  Molecule_name  IC50 (nM)  Status
0     Gefitinib       35.0  Potent
1   Osimertinib       15.0  Potent

In [7]:
df.to_csv('clean_egfr_compounds.csv', index=False)
print(f"CSV file successfully saved to your project folder!")

CSV file successfully saved to your project folder!

In [10]:
all_compounds = pd.DataFrame([
    {'Molecule': 'Gefitinib', 'IC50_nM': 35.0, 'Type': 'EGFR'},
    {'Molelcule': 'Osimertinib', 'IC50_nM': 15.0, 'Type': 'EGFR'},
    {'Molecule': 'Erlotinib', 'IC50_nM': 8.0, 'Type': 'EGFR'},
    {'Molecule': 'Aspirin', 'IC50_nM': 5200.0, 'Type': 'Non-specific'}
])
potent_df = all_compounds[all_compounds['IC50_nM']<30]
potent_df

    Molecule  IC50_nM  Type    Molelcule
1        NaN     15.0  EGFR  Osimertinib
2  Erlotinib      8.0  EGFR          NaN

In [11]:
import pandas as pd
from chembl_webresource_client.new_client import new_client

print("📡 Pulling live biological test records for human EGFR...")

try:
    # 1. Target search to lock onto human EGFR (Target ID: CHEMBL203)
    activities = new_client.activity
    egfr_raw_data = activities.filter(target_chembl_id="CHEMBL203").filter(standard_type="IC50")
    
    # 2. Extract the first 5 raw records into a list
    sample_records = list(egfr_raw_data[:5])
    
    # 3. Load the raw API output directly into a Pandas DataFrame
    raw_df = pd.DataFrame(sample_records)
    
    print("✅ Live data successfully retrieved!")
    
except Exception as e:
    print("❌ API connection failed. Server might be under maintenance.")
    print(f"Error details: {e}")

# Display the top rows of what ChEMBL sends back
raw_df[['molecule_chembl_id', 'standard_value', 'standard_units', 'type']]

📡 Pulling live biological test records for human EGFR...
✅ Live data successfully retrieved!

  molecule_chembl_id standard_value standard_units  type
0        CHEMBL68920           41.0             nM  IC50
1        CHEMBL68920          300.0             nM  IC50
2        CHEMBL68920         7820.0             nM  IC50
3        CHEMBL69960          170.0             nM  IC50
4        CHEMBL69960           40.0             nM  IC50

In [14]:
import pandas as pd
from chembl_webresource_client.new_client import new_client

print(f"Fetching a larget dataset of 20 EFGR recors...")
activities = new_client.activity
raw_results = activities.filter(target_chembl_id = "CHEMBL203").filter(standard_type = "IC50")
# Slice out 20 records
egfr_20_list = list(raw_results[:20])
df_raw = pd.DataFrame(egfr_20_list)
# Isolate the specific columns we care about
df_subset = df_raw[['molecule_chembl_id','standard_value','standard_units']].copy()
df_clean = df_subset.dropna(subset=['standard_value'])
df_clean['standard_value'] = pd.to_numeric(df_clean['standard_value'])
potent_compounds = df_clean[df_clean['standard_value'] < 100]
print(f"\n Sieve mechanism successful! ")
print(f"Found {len(potent_compounds)} potent inhibitors out of 20 raw records retrieved")
potent_compounds

Fetching a larget dataset of 20 EFGR recors...

 Sieve mechanism successful!
Found 3 potent inhibitors out of 20 raw records retrieved

   molecule_chembl_id  standard_value standard_units
0         CHEMBL68920           41.00             nM
4         CHEMBL69960           40.00             nM
17       CHEMBL304271            0.45             nM

In [19]:
import pandas as pd
from chembl_webresource_client.new_client import new_client

print("Step 1: Connecting to ChEMBL API Server")
activities = new_client.activity
raw_query = activities.filter(target_chembl_id = "CHEMBL203").filter(standard_type = "IC50")

print("Step 2: Downloading an expansive slice of 1000 raw records")
egfr_large_list = list(raw_query[:1000])
df_raw = pd.DataFrame(egfr_large_list)

print("Step 3: cleaning noise and missing values...")
df_subset = df_raw[['molecule_chembl_id', 'standard_value', 'standard_units']].copy()
df_clean = df_subset.dropna(subset=['standard_value']).copy()
df_clean['standard_value'] = pd.to_numeric(df_clean['standard_value'])

print("Step 4: Sifting for potent drug inhibitors (<100nM)... ")
potent_compounds = df_clean[df_clean['standard_value'] < 100]
# Deduplicate
unique_count = potent_compounds['molecule_chembl_id'].nunique()
print("Done")
print(f"Total raw records evaluated: {len(df_raw)}")
print(f"Potent entries remaining: {len(potent_compounds)}")
print(f"Total unique molecules discovered: {unique_count}")

potent_compounds.to_csv("egfr_potent_inhibitors.csv", index = False)
print("File successfully saved as: 'egfr_potent_inhibitors.csv' ")
potent_compounds.head()

Step 1: Connecting to ChEMBL API Server
Step 2: Downloading an expansive slice of 1000 raw records
Step 3: cleaning noise and missing values...
Step 4: Sifting for potent drug inhibitors (<100nM)...
Done
Total raw records evaluated: 1000
Potent entries remaining: 296
Total unique molecules discovered: 216
File successfully saved as: 'egfr_potent_inhibitors.csv'

   molecule_chembl_id  standard_value standard_units
0         CHEMBL68920           41.00             nM
4         CHEMBL69960           40.00             nM
17       CHEMBL304271            0.45             nM
30       CHEMBL136491           14.00             nM
41       CHEMBL137364           64.00             nM